import { Plugin, Notice, Editor, MarkdownView } from "obsidian";
import { P360SettingTab, P360Settings, DEFAULT_SETTINGS } from "./settings";
import { MoodView, VIEW_TYPE_MOOD } from "./views/mood-widget";
import { fetchBiometricData, getProviderDisplayName } from "./lib/data";
import {
  getWorkoutDecision,
  getDrinkDecision,
  getWhyDecision,
  getMoodDecision,
  BiometricData,
} from "@p360/core";

export default class P360Plugin extends Plugin {
  settings: P360Settings;

  async onload(): Promise<void> {
    await this.loadSettings();

    // Register settings tab
    this.addSettingTab(new P360SettingTab(this.app, this));

    // Register mood view
    this.registerView(VIEW_TYPE_MOOD, (leaf) => new MoodView(leaf, this));

    // Add ribbon icon
    this.addRibbonIcon("activity", "P360 Daily Check", async () => {
      await this.insertDailyCheck();
    });

    // Add commands
    this.addCommand({
      id: "p360-daily-check",
      name: "Insert Daily Check",
      editorCallback: async (editor: Editor) => {
        await this.insertDailyCheckAtCursor(editor);
      },
    });

    this.addCommand({
      id: "p360-workout",
      name: "Insert Workout Recommendation",
      editorCallback: async (editor: Editor) => {
        await this.insertWorkout(editor);
      },
    });

    this.addCommand({
      id: "p360-drink",
      name: "Insert Drink Guide",
      editorCallback: async (editor: Editor) => {
        await this.insertDrink(editor);
      },
    });

    this.addCommand({
      id: "p360-mood",
      name: "Open Mood Widget",
      callback: async () => {
        await this.activateMoodView();
      },
    });

    this.addCommand({
      id: "p360-refresh",
      name: "Refresh Biometric Data",
      callback: async () => {
        await this.refreshData();
      },
    });

    console.log("P360 plugin loaded");
  }

  onunload(): void {
    console.log("P360 plugin unloaded");
  }

  async loadSettings(): Promise<void> {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }

  async saveSettings(): Promise<void> {
    await this.saveData(this.settings);
  }

  // ============================================
  // Data Fetching
  // ============================================

  private async getBiometricData(): Promise<BiometricData | null> {
    const { token, provider } = this.settings;
    if (!token) {
      new Notice("Please configure your device token in P360 settings");
      return null;
    }

    try {
      return await fetchBiometricData(token, provider);
    } catch (error) {
      console.error("Failed to fetch biometric data:", error);
      new Notice("Failed to fetch biometric data. Check your token.");
      return null;
    }
  }

  // ============================================
  // Commands
  // ============================================

  private async insertDailyCheck(): Promise<void> {
    const view = this.app.workspace.getActiveViewOfType(MarkdownView);
    if (!view) {
      new Notice("Please open a note first");
      return;
    }
    await this.insertDailyCheckAtCursor(view.editor);
  }

  private async insertDailyCheckAtCursor(editor: Editor): Promise<void> {
    const data = await this.getBiometricData();
    if (!data) return;

    const { provider } = this.settings;
    const deviceName = getProviderDisplayName(provider);
    const workout = getWorkoutDecision(data);
    const drink = getDrinkDecision(data);

    const today = new Date().toLocaleDateString("en-US", {
      weekday: "long",
      year: "numeric",
      month: "long",
      day: "numeric",
    });

    const content = `
## P360 Daily Check
*${today} | ${deviceName}*

### Biometrics
| Metric | Value | Status |
|--------|-------|--------|
| Readiness | ${data.readinessScore ?? "?"}/100 | ${this.getStatusEmoji(data.readinessScore)} |
| Sleep | ${data.sleepScore ?? "?"}/100 | ${this.getStatusEmoji(data.sleepScore)} |
| HRV | ${this.formatHrv(data.hrvBalance)} | ${this.getHrvStatusEmoji(data.hrvBalance)} |
| RHR | ${data.restingHR ?? "?"} bpm | |

### Workout
> ${workout.emoji} **${workout.headline}**
> ${workout.subheadline}

${workout.reasoning.map((r) => `- ${r}`).join("\n")}

**Intensity Guide:**
- Cardio: ${workout.intensityGuide.cardio || "N/A"}
- Weights: ${workout.intensityGuide.weights || "N/A"}
- RPE: ${workout.intensityGuide.rpe || "N/A"}

### Drink Limit
> ${drink.emoji} **${drink.headline}**

| Drinks | Impact |
|--------|--------|
| ${drink.greenLimit} | ${drink.impacts[drink.greenLimit - 1]?.recoveryTime || "OK"} |
| ${drink.yellowLimit} | ${drink.impacts[drink.yellowLimit - 1]?.recoveryTime || "Caution"} |
| ${drink.redThreshold}+ | ${drink.impacts[Math.min(drink.redThreshold, 4)]?.recoveryTime || "Recovery needed"} |

---
*Generated by P360*
`;

    editor.replaceSelection(content.trim());
    new Notice("Daily check inserted!");
  }

  private async insertWorkout(editor: Editor): Promise<void> {
    const data = await this.getBiometricData();
    if (!data) return;

    const decision = getWorkoutDecision(data);

    const content = `
> [!${this.getCalloutType(decision.verdict)}] ${decision.emoji} ${decision.headline}
> ${decision.subheadline}
>
> **Readiness:** ${data.readinessScore ?? "?"}/100 | **HRV:** ${this.formatHrv(data.hrvBalance)} | **Sleep:** ${data.sleepScore ?? "?"}/100
>
> ${decision.reasoning.map((r) => `- ${r}`).join("\n> ")}
`;

    editor.replaceSelection(content.trim());
    new Notice("Workout recommendation inserted!");
  }

  private async insertDrink(editor: Editor): Promise<void> {
    const data = await this.getBiometricData();
    if (!data) return;

    const decision = getDrinkDecision(data);

    const content = `
> [!${this.getCalloutType(decision.verdict)}] ${decision.emoji} ${decision.headline}
> ${decision.subheadline}
>
> **Tonight's Limits:**
> - 🟢 ${decision.greenLimit} drinks: ${decision.impacts[decision.greenLimit - 1]?.recoveryTime || "OK"}
> - 🟡 ${decision.yellowLimit} drinks: ${decision.impacts[decision.yellowLimit - 1]?.recoveryTime || "Caution"}
> - 🔴 ${decision.redThreshold}+ drinks: ${decision.impacts[Math.min(decision.redThreshold, 4)]?.recoveryTime || "Recovery needed"}
`;

    editor.replaceSelection(content.trim());
    new Notice("Drink guide inserted!");
  }

  private async activateMoodView(): Promise<void> {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_MOOD);

    if (leaves.length === 0) {
      const leaf = this.app.workspace.getRightLeaf(false);
      if (leaf) {
        await leaf.setViewState({ type: VIEW_TYPE_MOOD, active: true });
        this.app.workspace.revealLeaf(leaf);
      }
    } else {
      this.app.workspace.revealLeaf(leaves[0]);
    }
  }

  private async refreshData(): Promise<void> {
    const data = await this.getBiometricData();
    if (data) {
      new Notice(
        `Data refreshed: Readiness ${data.readinessScore ?? "?"}, Sleep ${data.sleepScore ?? "?"}`
      );
    }
  }

  // ============================================
  // Helpers
  // ============================================

  private getStatusEmoji(score: number | null): string {
    if (score === null) return "❓";
    if (score >= 85) return "🟢";
    if (score >= 70) return "🟡";
    if (score >= 50) return "🟠";
    return "🔴";
  }

  private getHrvStatusEmoji(hrvBalance: number | null): string {
    if (hrvBalance === null) return "❓";
    const diff = hrvBalance - 50;
    if (diff >= 10) return "🟢";
    if (diff <= -10) return "🔴";
    return "🟡";
  }

  private formatHrv(hrvBalance: number | null): string {
    if (hrvBalance === null) return "N/A";
    const diff = hrvBalance - 50;
    if (diff > 0) return `+${diff}%`;
    return `${diff}%`;
  }

  private getCalloutType(verdict: string): string {
    switch (verdict) {
      case "train_hard":
      case "good":
        return "success";
      case "moderate":
      case "train_light":
        return "warning";
      case "rest":
      case "skip":
        return "danger";
      default:
        return "info";
    }
  }
}
